version: "3.9"
services:
  angularapp:
    image: alexsuch/angular-cli:12.2.10
    command: ng serve --host=0.0.0.0 --watch=false --live-reload=false
    working_dir: /app
    volumes:
      - "./app:/app"
    ports:
      - "4200:4200"
